### ISSUE TITLE
Swift 4 - Implicit declaration of function'sqlite3_key' is invalid in C99 

### ISSUE THREAD

**Issue by shaharukhs** [flipacholas/EncryptedDATAStack#1]
HI i am getting this error while building,

`Implicit declaration of function'sqlite3_key' is invalid in C99`

I am unable to build using `xcode 9` and `Swift 4`

**Comment by flipacholas** [comment]
This is because cocoapods is getting an older version of Encrypted Core Data.
Add this to your pod file:   `pod 'EncryptedCoreData', :git => 'https://github.com/project-imas/encrypted-core-data'`

**Comment by flipacholas** [comment]
Included on README
