### ISSUE TITLE
Missing old model, cannot check database

### ISSUE THREAD

**Issue by abhishek17jas** [flipacholas/EncryptedDATAStack#3]
Hi,

I am getting the below mentioned error:

CoreData: error: -addPersistentStoreWithType:EncryptedStore configuration:(null) URL:file:///Users/Abhishek/Library/Developer/CoreSimulator/Devices/FBB63F98-EF2E-42CE-89FA-86F424F00993/data/Containers/Data/Application/2BB84248-7D2E-4B54-BBFA-EB258363795D/Documents/mobilecore.sqlite options:{
    EncryptedStorePassphrase = ABC;
    NSInferMappingModelAutomaticallyOption = 1;
    NSMigratePersistentStoresAutomaticallyOption = 1;
} ... returned error Error Domain=EncryptedStoreErrorDomain Code=6001 "(null)" UserInfo={EncryptedStoreErrorMessage=Missing old model, cannot check database} with userInfo dictionary {
    EncryptedStoreErrorMessage = "Missing old model, cannot check database";
}

And the application is crashing.

Thanks

**Comment by flipacholas** [comment]
Back then when I rebased to 7.0.3 of DATAStack I was hoping that it would improve the library but it got more complicated at the end. So I think the 2 possible solutions are:

- Rebase the project again to the latest release: Unfortunately I don't have much time right now.
- Use 2.0.0 (Change your podfile): Always worked well for me.

**Comment by abhishek17jas** [comment]
Hi,

Changed to 2.0.0 and not getting same error. It worked 👍 

But, there is a problem in fetching data from the db. Whenever there is one-to-many relationship, the many relationship SET objects have nil value ( All the values are nil ).

Do I need to check for some settings to solve the issue.

Thanks

**Comment by flipacholas** [comment]
I remember happening to me when I was using common key names ('order', 'name', etc), somehow that messed up the fetch. Maybe changing the names will help you?

**Comment by abhishek17jas** [comment]
Hi,
The mentioned changes have solved the issue. 👍 

We have another issue:

We have been following model versioning. And the previous version does not have this Encrypted Core Data implementation. 
In our new version we have implemented the Encrypted Core Data feature. When we try to run this new version on top of installed older version (Not with Encrypted Core Data feature) the application is crashing.

Please have a look at below error logs:

1)
UserInfo={NSLocalizedDescription=Incorrect passcode, NSUnderlyingError=0x604000449720 {Error Domain=NSSQLiteErrorDomain Code=26 "(null)" UserInfo={EncryptedStoreErrorMessage=file is not a database}}}
{
    NSLocalizedDescription = "Incorrect passcode";
    NSUnderlyingError = "Error Domain=NSSQLiteErrorDomain Code=26 \"(null)\" UserInfo={EncryptedStoreErrorMessage=file is not a database}";
}
Incorrect passcode

2)
CoreData: error: Illegal attempt to save to a file that was never opened.  "This NSPersistentStoreCoordinator has no persistent stores (unknown).  It cannot perform a save operation.".  Last recorded error = Error Domain=EncryptedStoreErrorDomain Code=6000 "(null)" UserInfo={NSFilePath=/Users/Abhishek/Library/Developer/CoreSimulator/Devices/FBB63F98-EF2E-42CE-89FA-86F424F00993/data/Containers/Data/Application/9ECA7AC6-BAE8-434E-B21C-D820857C5146/Library/Application Support/com.emishealth.mobilecore.stores/mobilecore.sqlite} / {
    NSFilePath = "/Users/Abhishek/Library/Developer/CoreSimulator/Devices/FBB63F98-EF2E-42CE-89FA-86F424F00993/data/Containers/Data/Application/9ECA7AC6-BAE8-434E-B21C-D820857C5146/Library/Application Support/com.emishealth.mobilecore.stores/mobilecore.sqlite";
}

Thanks

**Comment by flipacholas** [comment]
Sorry migration can't be done automatically, encrypted core data replaces the conventional NSIncrementalStore and makes it work exclusively with an encrypted database. You'll have to generate a blank database with EncryptedDATAStack and populate it with some sort of script. There are a couple of clients like DB Browser for SQLite which support the encryption used (sqlcipher).

**Comment by abhishek17jas** [comment]
Hi,

 As per my understanding, do we need to replace the existing non-encrypted DB (previous data) with the encrypted empty DB and recreate the STACK again.
Also what does the mentioned line means "You'll have to generate a blank database with EncryptedDATAStack and populate it with some sort of script.". 

Please help in resolving this.

Thanks

**Comment by flipacholas** [comment]
I mean that there is no easy way to migrate your old database to the encrypted one, so one thing you could do is creating a blank encrypted database and fill your stuff on it. Creating a script may help you but bear in mind that the new encrypted database uses sqlcipher so you have to find a client (like DB Browser for SQLite) which supports this encryption system.

**Comment by abhishek17jas** [comment]
Hi,

Now I have better understanding. 👍 

Thanks

**Comment by abhishek17jas** [comment]
HI,

I am able to implement the Encrypted DB and it works fine. But there is an issue related to the creation of new ENTITY or ATTRIBUTE to the next migrated version of the model e.g suppose my existing version is v1 and I created new ENTITY or ATTRIBUTE for the version(v1) and when I create a new migrated version v2 the previously created ENTITY or ATTRIBUTE is not created for the new version(v2). I am doing all the operations in ENCRYPTED Database environment and following Core Data Light Weight Migration.

I am using "2.0.0" version of the framework.

Please help,as I am almost done with the implementation and this is only the issue came to us.

Thanks

**Comment by abhishek17jas** [comment]
Was able to solve the issue.
