### ISSUE TITLE
Light weight migration with encrypted database

### ISSUE THREAD

**Issue by VivoEx** [flipacholas/EncryptedDATAStack#4]
I am trying to migrate my database version to include a new attribute to an entity, but the newly added attributes are not created when I try to view them in the DB viewer. My previous db version is an encrypted version too.
Even the entity thats created in the migrated version is missing. Do we need to do any extra step to perform light weight migration with this ?

**Comment by VidyaRameshkumarEmis** [comment]
Even the entity thats created in the migrated version is missing. Do we need to do any extra step to perform light weight migration with this ?
